title: GE Scraping
description: Site de Gruppo de Estudos de Scraping com Python
author: Edson Araújo
logo: #/hcz-jekyll-blog/static/img/avatar.png
github: gescraping 
about: Grupo de estudos

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: gescraping
google_analytics: ""

share:
  twitter_username: ""
  fb_appid: "" 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
