title: GE Scraping
description: Site de Grupo de Estudos de Scraping com Python
author: Edson Araújo
logo: ""  
github: gescraping 
about: Grupo de estudos

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: gescraping-github-io
google_analytics: ""

share:
  twitter_username: ""
  fb_appid: "" 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
